/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#4361ee",
        "on-primary": "#ffffff",
        "primary-container": "#dbe4ff",
        "on-primary-container": "#3f37c9",
        secondary: "#4895ef",
        "on-secondary": "#ffffff",
        "secondary-container": "#e0f2fe",
        "on-secondary-container": "#0369a1",
        tertiary: "#f72585",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ffdeeb",
        "on-tertiary-container": "#a21caf",
        error: "#e63946",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f0f2f5",
        "on-background": "#1b1b1f",
        surface: "#f0f2f5",
        "on-surface": "#1b1b1f",
        "surface-variant": "#e1e2ec",
        "on-surface-variant": "#44464f",
        outline: "#74777f",
        "outline-variant": "#c4c6d0",
        "surface-container": "#eceef4",
        "surface-container-low": "#f2f4f8",
        "surface-container-high": "#e6e8ee",
        "surface-container-highest": "#e0e2e8",
        "surface-container-lowest": "#ffffff",
      },
      fontFamily: {
        quicksand: ["Quicksand", "sans-serif"],
        nunito: ["Nunito Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        xs: "4px",
        sm: "12px",
        md: "24px",
        lg: "40px",
        xl: "64px",
        gutter: "16px",
        margin: "24px",
      },
    },
  },
  plugins: [],
}
