/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#296956",
        "on-primary": "#ffffff",
        "primary-container": "#98d8c1",
        "on-primary-container": "#1e604e",
        secondary: "#30628a",
        "on-secondary": "#ffffff",
        "secondary-container": "#a1d1fe",
        "on-secondary-container": "#265a81",
        tertiary: "#765b06",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ecc76d",
        "on-tertiary-container": "#6c5200",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f7f9fb",
        "on-background": "#191c1e",
        surface: "#f7f9fb",
        "on-surface": "#191c1e",
        "surface-variant": "#e0e3e5",
        "on-surface-variant": "#404945",
        outline: "#707974",
        "outline-variant": "#bfc9c3",
        "surface-container": "#eceef0",
        "surface-container-low": "#f2f4f6",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
      },
      fontFamily: {
        quicksand: ["Quicksand", "sans-serif"],
        nunito: ["Nunito Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        xs: "4px",
        sm: "12px",
        md: "24px",
        lg: "40px",
        xl: "64px",
        gutter: "16px",
        margin: "24px",
      },
    },
  },
  plugins: [],
}
